### ISSUE TITLE
The application does not start on the emulator

### ISSUE THREAD

**Issue by tsepen** [ueno-llc/react-native-starter#226]
I run
`react-native start`

Then
`react-native run-android`

I see an error in the emulator (Android studio SDK 28 android 9) 
'Error: Unable to resolve module `./index` from ``: 

None of these files exist:
  * index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * index/index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
    at ModuleResolver.resolveDependency (/home/lomaz/www/befree_new_mobile/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (/home/lomaz/www/befree_new_mobile/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/home/lomaz/www/befree_new_mobile/node_modules/metro/src/node-haste/DependencyGraph.js:282:16)
    at /home/lomaz/www/befree_new_mobile/node_modules/metro/src/lib/transformHelpers.js:267:42
    at Server.<anonymous> (/home/lomaz/www/befree_new_mobile/node_modules/metro/src/Server.js:1088:41)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/lomaz/www/befree_new_mobile/node_modules/metro/src/Server.js:99:24)
    at _next (/home/lomaz/www/befree_new_mobile/node_modules/metro/src/Server.js:119:9)
::ffff:127.0.0.1 - - [12/Sep/2019:11:31:23 +0000] "GET /index.bundle?platform=android&dev=true&minify=false HTTP/1.1" 500 - "-" "okhttp/3.12.1"
'

I tried and it did not help
`react-native start --reset-cache`

**Comment by birkir** [comment]
Hey, so its looking for a index.js in your root directory.

Either

a) create a file in your root directory `./index.js` and the contents:
```js
require('./src/index');
```
b) Edit your entry point like its done here:
https://github.com/ueno-llc/react-native-starter/blob/master/android/app/build.gradle#L18
