### ISSUE TITLE
Can't run on Windows 10 at Android Emulator

### ISSUE THREAD

**Issue by marceloavf** [ueno-llc/react-native-starter#229]
**Describe the bug**
Can't make it run using `Super-Quick Start` on Windows 10.

**To Reproduce**
```
git clone git@github.com:ueno-llc/react-native-starter.git my-new-app
cd my-new-app
yarn
yarn rename "MyNewApp" com.ueno.mynewapp
react-native run-android
```

**Expected behavior**
Be able to run on emulator.

**Error**
```
Welcome to Gradle 5.4.1!

Here are the highlights of this release:
 - Run builds with JDK12
 - New API for Incremental Tasks
 - Updates to native projects, including Swift 5 support

For more details see https://docs.gradle.org/5.4.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :
MyNewApp D:\projects\test\ueno-test\android D:\projects\test\ueno-test\android
@react-native-community_async-storage D:\projects\test\ueno-test\node_modules\@react-native-community\async-storage\android D:\projects\test\ueno-test\android
app D:\projects\test\ueno-test\android\app D:\projects\test\ueno-test\android
detox D:\projects\test\ueno-test\node_modules\detox\android\detox D:\projects\test\ueno-test\android
react-native-code-push D:\projects\test\ueno-test\node_modules\react-native-code-push\android\app D:\projects\test\ueno-test\android
react-native-config D:\projects\test\ueno-test\node_modules\react-native-config\android D:\projects\test\ueno-test\android
react-native-firebase D:\projects\test\ueno-test\node_modules\react-native-firebase\android D:\projects\test\ueno-test\android
react-native-navigation D:\projects\test\ueno-test\node_modules\react-native-navigation\lib\android\app D:\projects\test\ueno-test\android
react-native-sentry D:\projects\test\ueno-test\node_modules\react-native-sentry\android D:\projects\test\ueno-test\android
react-native-version-number D:\projects\test\ueno-test\node_modules\react-native-version-number\android D:\projects\test\ueno-test\android

> Configure project :@react-native-community_async-storage
WARNING: The option setting 'android.enableD8.desugaring=false' is experimental and unsupported.
The current default is 'true'.


> Configure project :app
WARNING: The option setting 'android.enableD8.desugaring=false' is experimental and unsupported.
The current default is 'true'.


Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
A problem occurred evaluating project ':app'.
> A problem occurred starting process 'command './scripts/build-env.sh''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':app'.
> compileSdkVersion is not specified.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 3s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
A problem occurred evaluating project ':app'.
> A problem occurred starting process 'command './scripts/build-env.sh''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':app'.
> compileSdkVersion is not specified.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 3s

    at checkExecSyncError (child_process.js:629:11)
    at execFileSync (child_process.js:647:13)
    at runOnAllDevices (D:\projects\test\ueno-test\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:74:39)
    at buildAndRun (D:\projects\test\ueno-test\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:158:41)
    at then.result (D:\projects\test\ueno-test\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:125:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

### Environment
* React Native Starter version: v3.0.0
* React Native version: 0.61.0-rc.0 (2.0.1 cli)
* Platforms
  * [ ] iOS
  * [X] Android
* Device Info
  * [ ] Physical Device in Debug
  * [ ] Physical Device in Release
  * [X] Simulator in Debug
  * [ ] Simulator in Release

### Additional context

```

warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - react-native-code-push: https://microsoft.github.io/code-push
  - react-native-sentry: https://github.com/getsentry/react-native-sentry
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.
info Fetching system and libraries information...
System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    Memory: 9.89 GB / 31.90 GB
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.11.3 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5791312
```

**Comment by marceloavf** [comment]
https://github.com/ueno-llc/react-native-starter/blob/4e5c34e830c59d85a469f131445732d3817fc49e/android/app/build.gradle#L3-L11

I saw that on `build.gradle`, Maybe it's trying to run the second one? I'll try to comment it
